spring:
  rabbitmq:
    host: localhost
    username: mls-rabbitmq-user
    password: mls-rabbitmq-pass
application:
  geocoder:
    priority:
    requeue: true
  poi:
    sources:
      ehs.json: EHS
      hospitals.json:
      wrk.json:
logging:
  level:
    root: info
    at.wrk.fmd.mls: debug
