# Copy this to application-dev.yml and set the API key

spring:
  rabbitmq:
    host: localhost
    username: coceso-rabbitmq-user
    password: coceso-rabbitmq-pass
application:
  geocoder:
    priority: 3
    requeue: false
  gmaps:
    api-key: !!REQUIRED!!
logging:
  level:
    root: info
    at.wrk.coceso: debug
