spring:
  rabbitmq:
    host: localhost
    username: mls-rabbitmq-user
    password: mls-rabbitmq-pass
application:
  geocoder:
    priority: 2
    requeue: true
logging:
  level:
    root: info
    at.wrk.fmd.mls: debug
